#include <WiFi.h>

void PrintHtml(WiFiClient &client){
    client.println("<!DOCTYPE html>");
    client.println("<html lang=\"en\">");
    client.println("<head>");
    client.println("  <meta charset=\"UTF-8\">");
    client.println("  <title>WiFi & dexcom Setup</title>");
    client.println("  <style>");
    client.println("    body {");
    client.println("      font-family: Arial, sans-serif;");
    client.println("      background: #e6e6e6;");
    client.println("      padding: 20px;");
    client.println("    }");
    client.println("    .container {");
    client.println("      max-width: 400px;");
    client.println("      margin: auto;");
    client.println("      background: white;");
    client.println("      padding: 30px;");
    client.println("      border-radius: 10px;");
    client.println("      box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);");
    client.println("    }");
    client.println("    h2 {");
    client.println("      text-align: center;");
    client.println("      margin-bottom: 20px;");
    client.println("    }");
    client.println("    label {");
    client.println("      font-weight: bold;");
    client.println("    }");
    client.println("    input[type=\"text\"], input[type=\"password\"] {");
    client.println("      width: 100%;");
    client.println("      padding: 10px;");
    client.println("      margin: 10px 0 20px;");
    client.println("      border: 1px solid #ccc;");
    client.println("      border-radius: 5px;");
    client.println("    }");
    client.println("    button {");
    client.println("      width: 100%;");
    client.println("      padding: 12px;");
    client.println("      background-color: #007bff;");
    client.println("      color: white;");
    client.println("      border: none;");
    client.println("      border-radius: 5px;");
    client.println("      font-size: 16px;");
    client.println("      cursor: pointer;");
    client.println("    }");
    client.println("    button:hover {");
    client.println("      background-color: #0056b3;");
    client.println("    }");
    client.println("  </style>");
    client.println("</head>");
    client.println("<body>");
    client.println("");
    client.println("  <div class=\"container\">");
    client.println("    <h2>Levels Display Setup</h2>");
    client.println("    <form>");
    client.println("      <label for=\"ssid\">WiFi SSID</label>");
    client.println("      <input type=\"text\" id=\"wifi-ssid\" name=\"wifi_ssid\" required>");
    client.println("");
    client.println("      <label for=\"wifi-password\">WiFi Password</label>");
    client.println("      <input type=\"password\" id=\"wifi-password\" name=\"wifi_password\" required>");
    client.println("");
    client.println("      <label for=\"username\">Dexcom Username</label>");
    client.println("      <input type=\"text\" id=\"dexom-username\" name=\"dexcom_username\" required>");
    client.println("");
    client.println("      <label for=\"dexcom-password\">Dexcom Password</label>");
    client.println("      <input type=\"password\" id=\"dexcom-password\" name=\"dexcom_password\" required>");
    client.println("");
    client.println("      <button type=\"submit\">Save Settings</button>");
    client.println("      <label id = \"error_label\" style=\"color: crimson;\"></label>");
    client.println("    </form>");
    client.println("  </div>");
    client.println("");
    client.println("</body>");
    client.println("</html>");

}